## This configuration file should be used with 'init-aws-director.yml' for deployment. Generated values will be added to this file on first deployment. 
##
## To deploy (requires BOSH v2 CLI) - `bosh create-env init-aws-director.yml --vars-store init-aws-director-config.yml`

aws-region: 
aws-availability-zone: 
aws-subnet-id: 

aws-access-key-id: 
aws-secret-access-key: 
aws-default-security-group: 
 
# Manifest assumes 10.0.0.0/24 subnet
internal-ip: 
external-ip: 

# Format is 32 character length hexadecimal string
credhub-encryption-key: 

# Key name and local path to SSH key
aws-ssh-key-name: 
ssh-username: 
ssh-path-to-private-key: 

