## This configuration file should be used with 'init-gcp-director.yml' for deployment. Generated values will be added to this file on first deployment.
##
## To deploy (requires BOSH v2 CLI) - `bosh create-env init-gcp-director.yml --vars-store init-gcp-director-config.yml`

gcp-zone: 
gcp-network-name: 
gcp-subnet-name: 

# Service account JSON key escaped in string format
escaped-gcp-json-key:

# Manifest assumes 10.0.0.0/24 subnet
internal-ip: 
external-ip: 

# Format is 32 character length hexadecimal string
credhub-encryption-key:

# SSH username and local path to SSH key
ssh-username: 
path-to-ssh-private-key:
