---
platform: linux
image: docker:///pcfseceng/sec-eng-ci

inputs:
  - name: task-repo
  - name: credhub-release-tarball

outputs:
  - name: release-name-output

run:
  path: task-repo/ci/tasks/release-name/task.sh

params:
  RELEASE_NAME_OUTPUT_PATH: release-name-output
